Q.1)Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [97]:
import numpy as np

In [98]:
def ATV_matrix(input, n, increasing=True):
    if increasing:
        output = np.array([[x**j for j in range(n)] for x in input])
    else:
        output = np.array([[x**(n-j-1) for j in range(n)] for x in input])
    return output

In [99]:
output_matrix1 = ATV_matrix([1,2,3,4,5], 3, False)
print(output_matrix1)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [103]:
output_matrix2 = ATV_matrix([1,2,3,4,5], 3, True)
print(output_matrix2)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


In [101]:
output_matrix3 = ATV_matrix([1,2,3,4,5], 5, False)
print(output_matrix3)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Q.2)
Problem Statement: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
 
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [107]:
def moving_average(input, k):
    
    total_sequence = len(input)-k+1
    output =[0]* total_sequence
    count=0
    for i in range(total_sequence):
        sum=0
        for j in range(k):
            sum+=input[count+j]
        count+=1
        avg=sum/k
        output[i] = avg
    return output

In [114]:
output = np.round(moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3),2)
print(output)

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]


In [119]:
output1 = np.round(moving_average([10,20,30,40,50,60,70,80,90,100], 4), 2)
print(output1)

[25. 35. 45. 55. 65. 75. 85.]
